config/routes.rb
Rails.application.routes.draw do
  resources :user_personalities do
    get '/graphics', to: 'pages#graphics'
    resources :categories, except: :index do
      resources :transactions, except: %i[index show] do
        resources :notes
      end
    end
  end
  devise_for :users
  root 'pages#home'
end

app/views/pages/_transaction.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">
          Transaction info
        </span>
        <p>
          <% if transaction.important == true %>
            <strong class="important-transaction">Important!</strong>
          <% end %>
        </p>
        <table class="centered blue-grey darken-2">
          <tbody>
          <% transaction.notes.each do |note| %>
          <tr>
            <td>
              <%= simple_format(truncate(note.description, length: 35)) %>
            </td>
          </tr>
          <% end %>
          </tbody> 
        </table>
        <br>
          <% if transaction.withdrawal %>
            <h1><%= '%.2f' %(-transaction.amount_cents.to_f / 100) %>
                <%= transaction.amount_currency %>
            </h1>
          <% else %>
            <h1><%= '%.2f' %(transaction.amount_cents.to_f / 100) %>
                <%= transaction.amount_currency %>
            </h1>
          <% end %>
          <p> 
          Created <%= transaction.created_at.strftime("%H:%M  %d.%m.%Y") %> <br>
          Edited <%= transaction.updated_at.strftime("%H:%M  %d.%m.%Y")  %>
          </p>
      </div>
    </div>
  </div>
</div>

app/views/pages/error.html.erb
<h1>Something wen't wrong</h1>
<strong><%= @expection %></strong>

app/views/pages/graphics.html.erb
<div class="container center">
  <br>
  <%= pie_chart @personality.categories.group(:name).sum(:amount_cents) %>
  <br>
  <%= form_for(@personality, url: user_personality_graphics_path(@personality), method: :get) do |f| %>
    <div class="form-inputs row">
      <div class="input-field col s6 offset-s3">
        <strong>Choose date range</strong>
        <p>Date from</p>
        <%= text_field_tag 'search[date_from]', @date_from %>
        <p>Date to</p>
        <%= text_field_tag 'search[date_to]', @date_to %>
      </div>
    </div>
    <div class="form-actions center">
      <%= f.submit 'Search transactions', class: "btn waves-effect white-text light-green darken-2" %>
    </div>
  <% end %>
  <br>
  <% @personality.categories.each do |category|%>
    <h1 style="color: black;"><%= category.name %></h1>
    <h2 style="color: black;">List of transactions</h2>
    <h3 style="color: red;">Withdrawals</h1>
    <% category.transactions.where({ created_at: @date_from..@date_to })
               .select{ |transaction| transaction["withdrawal"] == true }.each do |transaction| %>
      <%= render partial: "transaction", object: transaction %>
    <% end %>
    <h3 style="color: green;">Incomes</h3>
    <% category.transactions.where({ created_at: @date_from..@date_to })
               .select{ |transaction| transaction["withdrawal"] == false }.each do |transaction| %>
      <%= render partial: "transaction", object: transaction %>
    <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container center">
  <h1>Welcome <%= current_user.email %></h1>
  <%= link_to 'List of all personalities', user_personalities_path, 
      class: "waves-effect waves-light btn light-green darken-2" %>
  <%= link_to 'Create personality', new_user_personality_path, 
      class: "waves-effect waves-light btn light-green darken-2" %>
</div>